### ISSUE TITLE
Wrong data with southernMonths

### ISSUE THREAD

**Issue by drallieiv** [maael/nook#5]
Seems that you put in your fish/bug data that Souther Month are the opposite of Northern month.

That lands true for fish/bugs that are available for 6 month, but wrong for all other cases.

It should be offseted by 6 months (plus or minus doesn't change anything).

Suckerfish for example is June to Sept Northern, but October to May Southern in your dataset.
Where it should be December to March.

Same seems to applies to all Southern data

**Comment by maael** [comment]
Hey, thanks for spotting this!

I've fixed this [here](https://github.com/maael/nook/commit/a3e71ff7b437e7b0614526ee43b74b5b64e08465) by changing to calculate the southern hemisphere values by offsetting them by +6 like you suggested, instead of the inversion of the northern months like I was previously doing.
